# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish ShopX Docker Image on Docker Hub

on:
  push:
    branches: [ "main" ]


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
    #- uses: actions/checkout@v3
    - name: docker login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_HUB_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASS}}
        REPO_NAME: ${{secrets.REPO_NAME}}
        readme-filepath: ./README.md
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Get current date # get the date of the build
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_HUB_USER}}/${{secrets.REPO_NAME}}:${{steps.date.outputs.date}}
      
    - name: Push_Image
      run: docker push ${{secrets.DOCKER_HUB_USER}}/${{secrets.REPO_NAME}}:${{steps.date.outputs.date}}